export default function FAQPage() {
  const faqs = [
    {
      q: "Is this free?",
      a: "Yes. The report is completely free while the product is in early access. We may introduce premium features in the future, but the core report will always remain accessible.",
    },
    {
      q: "Is this scientific?",
      a: "No. Personal Metadata is a symbolic reflection and entertainment tool. It combines numerology, astrology, and Chinese zodiac traditions as frameworks for self-reflection, not as scientific fact.",
    },
    {
      q: "Do I need my birth time?",
      a: "No. Birth time is optional. It may allow more detailed symbolic interpretations (like Moon and Rising signs) in future updates, but your core report works perfectly with just your birth date.",
    },
    {
      q: "Why do you ask for my email?",
      a: "To send you your report link so you can access it again later. We also use it to notify you of new features if you opt in. We never sell your email or send spam.",
    },
    {
      q: "Can I delete my data?",
      a: "Yes. You can request deletion of your data at any time. We also automatically delete reports after 12 months of inactivity.",
    },
    {
      q: "Is this medical or psychological advice?",
      a: "No. This should never replace professional advice from a doctor, therapist, counselor, or other qualified professional. If you are experiencing a crisis, please reach out to a professional immediately.",
    },
    {
      q: "How accurate is the report?",
      a: "The calculations (numerology, Sun sign, Chinese zodiac) follow established symbolic systems. The interpretations are generated by AI and meant to provoke reflection. Take what resonates, leave what does not.",
    },
  ];

  return (
    <main className="min-h-screen bg-ivory py-20">
      <div className="max-w-2xl mx-auto px-5 md:px-8">
        <h1 className="font-serif text-3xl md:text-4xl text-ink mb-12">
          Frequently Asked Questions
        </h1>
        <div className="space-y-8">
          {faqs.map((faq, i) => (
            <div key={i} className="p-6 bg-white rounded-card border border-ink/10">
              <h2 className="text-ink font-semibold text-lg mb-3">{faq.q}</h2>
              <p className="text-ink-soft leading-relaxed">{faq.a}</p>
            </div>
          ))}
        </div>
      </div>
    </main>
  );
}
