export default function TermsPage() {
  return (
    <main className="min-h-screen bg-midnight py-20">
      <div className="max-w-2xl mx-auto px-5 md:px-8">
        <h1 className="font-serif text-3xl md:text-4xl text-soft-white mb-8">
          Terms of Service
        </h1>
        <div className="prose prose-invert prose-lg max-w-none text-mist-gray">
          <p className="mb-4">
            By using Personal Metadata, you agree to these terms. Please read them carefully.
          </p>
          <h2 className="text-soft-white text-xl mt-8 mb-4">Nature of the Service</h2>
          <p className="mb-4">
            Personal Metadata is a free web application that generates symbolic
            self-reflection reports based on numerology, astrology, and Chinese zodiac
            systems. It is designed for entertainment, reflection, and self-awareness
            purposes only.
          </p>
          <h2 className="text-soft-white text-xl mt-8 mb-4">No Professional Advice</h2>
          <p className="mb-4">
            The reports generated by Personal Metadata do not constitute scientific,
            medical, psychological, legal, financial, or professional advice. Do not use
            this service to make decisions that require professional consultation.
          </p>
          <h2 className="text-soft-white text-xl mt-8 mb-4">User Responsibilities</h2>
          <ul className="list-disc pl-5 space-y-2">
            <li>You must be at least 16 years old to use this service</li>
            <li>You provide accurate information voluntarily</li>
            <li>You understand the symbolic nature of the reports</li>
          </ul>
          <h2 className="text-soft-white text-xl mt-8 mb-4">Limitation of Liability</h2>
          <p className="mb-4">
            Personal Metadata and its creators are not liable for any decisions made or
            actions taken based on the reports generated. The service is provided as is
            without warranties of any kind.
          </p>
        </div>
      </div>
    </main>
  );
}
